stages:
  get-features:
    cmd: python3 scripts/dataScripts/get_features.py data/train.csv
    deps:
    - data/train.csv
    - scripts/dataScripts/get_features.py
    outs:
    - data/stage1
  fill-na:
    cmd: python3 scripts/dataScripts/fill_na.py  data/stage1/train.csv
    deps:
    - data/stage1/train.csv
    - scripts/dataScripts/fill_na.py
    outs:
    - data/stage2
  change_text:
    cmd: python3 scripts/dataScripts/change_text_to_numeric.py data/stage2/train.csv
    deps:
    - data/stage2/train.csv
    - scripts/dataScripts/change_text_to_numeric.py
    outs:
    - data/stage3
  split:
    cmd: python3 scripts/dataScripts/train_test_split.py data/stage3/train.csv
    deps:
    - data/stage3/train.csv
    - scripts/dataScripts/train_test_split.py
    outs:
    - data/stage4
  train:
    cmd: python3 scripts/model_learn/dt.py data/stage4/train.csv model.pkl
    deps:
      - data/stage4/train.csv
      - scripts/model_learn/dt.py
    params:
      - train.seed
      - train.normalize
    outs:
      - models/model.pkl
  evaluate:
    cmd: python3 scripts/model_learn/evaluate.py data/stage4/test.csv models/model.pkl
    deps:
    - data/stage4/test.csv
    - models/model.pkl
    - scripts/model_learn/evaluate.py
    metrics:
    - evaluate/metrics.json:
        cache: false